[package]
name = "who-asked"
version = "0.1.0"
edition = "2021"
licenses = "GPL-V3"
autho = "Froxcey"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
